# Docker Desktop / WSL 本地开发：broker 必须向宿主客户端通告映射端口地址。
brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
namesrvAddr=rocketmq-namesrv:9876
brokerIP1=127.0.0.1
listenPort=10911
autoCreateTopicEnable=true
deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
